project:
  type: website
  output-dir: docs
  resouces:
    - sta199-s23-2-syllabus.pdf #need to update

website:
  page-navigation: true
  title: "STA 199"
  description: "Homepage for STA 199 - Introduction to Data Science at Duke University, Summer 2023, First Session."
  site-url: "https://sta199-summer-1.github.io/"

  repo-url: https://github.com/sta199-summer-1/sta199-summer-1.github.io/
  repo-actions: [edit, issue]

  opengraph: true

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Elijah Meyer"
    background: "#f7bd2a" # Orange - Summer 2023

  sidebar:
    background: "#f7bd2a" # Orange - Summer 2023
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sta199-summer-1/sta199-summer-1.github.io
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: person-fill
        text: "Sakai"
        menu:
          - text: Gradescope #update when I get access
            url: https://sakai.duke.edu/portal/site/d30a7ca1-ff1b-46f1-99b7-0555e181b10a/page/18625ab1-2a56-4c98-b345-bf841f60f328
          - text: Gradebook
            url: https://sakai.duke.edu/portal/site/d30a7ca1-ff1b-46f1-99b7-0555e181b10a/tool/2022220a-762f-4c4e-b81c-cbd494f4debc/

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing-cheatsheets.qmd
            text: Cheatsheets
      - section: "Project"
        contents:
          - href: project-description-summer.qmd
            text: Description
          - href: project-tips-resources.qmd
            text: Tips + resources
      - section: "Example Work"
        contents:
          - href: project-examples.qmd
            text: Student Project Examples


format:
  html:
    theme:
      light: [cosmo, style/sta199.scss]
      dark: [cosmo, style/sta199.scss, style/dark.scss]
    linkcolor: "#1F7349" # Pantone Amazon - Fall 2022
    toc: true
    code-copy: true
    code-overflow: wrap
    code-link: true
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
