---
title: "Group Work + Merge Conflicts"
subtitle: "Lab-4"
date: "Feburary 21st 2023"
format: revealjs
---


## Checklist

-- Go to the course [GitHub org](https://github.com/sta199-s23-2) and find your `lab-04` (repo name will be suffixed with your GitHub TEAM name).

-- Clone the repo in your container, open the Quarto document in the repo

-- When cloning, use the given name (or come up with one if none is given) that everyone is going to pull so they have one rproj file in the repo. In short, name your project the same name as your other teammates. 

-- Do not start these labs early. Communication is key when working together using GitHub 

## Announcements

-- HW-2 due Friday (11:59) - Gradescope

-- Labs due in 1 week (11:59) - Gradescope

-- Do not forget to select pages!!

-- Do not forget to add group members to lab submission!

## Lab submission 

-- Only one user needs to submit 

-- Attach all team members to submission or they will not receive credit 

-- Clearly communicate who is going to turn in the lab submission 

## Group Work: Why? 

-- see problems and learn from different perspectives 

-- practice communication skills 

-- helps improve problem solving skills 

-- group work is part of the real-world; practice this skill now! 

## Group Work: Good Habits 

-- Establish a clear line of communication (Slack or other)

-- If you can not show up to lab, inform your group mates + come up with a plan 

-- Work with your group. Share ideas. Teach eachother. Do not tackle the lab + project as a bunch of individual assignments 

## Merge Conflicts 

-- happen when you merge branches that have competing commits, and Git needs your help to decide which changes to incorporate in the final merg

## General Tips 

-- **COMMIT EVERYTHING** when making changes. Ex. both the qmd and pdf of lab-4. 

-- **ALWAYS** pull before you start working + making changes 


## Fixing a Merge Conflict 

-- Go through the steps from Lab-4; find the strange symbols; change document to include only the information that you want 

## Fixing a Merge Conflict 

"Burn it down and start over" 

-- This is not recommended. However sometimes merge conflicts are past the point of fixing. If this is you, and you no longer have any changes in the document you wish to keep, you can delete your repo and reclone what is on GitHub in order to sync back up with your group. 
