---
title: "Project Proposal Lab"
subtitle: "Lab 6"
date: "March 7th, 2023"
---

## Group Dynamic 

-- Are you communicating? 

-- Are expectations clear? 

-- Everyone needs to contribute 

## Group Dynamic

-- If not, reach out to your lab leader 

-- A student's name does not go on any submission where they do not contribute nor communicate with other group members

-- Group Evals 

## Merge Conflicts (Do's and Don'ts)

-- Make sure to ALWAYS pull before starting to work 

-- It is okay to work on different sections at the same time (auto merge)

-- It is not okay to work on the same sections at the same time 

## Fixing Merge Conflicts 

-- Pull + Delete the changes that you do not want reflected (see Merge Conflict Lab) 

-- Do not change the branch you are working in 

-- "Delete and start over" method if you are many branches ahead (not ideal)\

## Project Tips 

-- Pick topics everyone find interesting + exciting 

-- Involve everyone in which data sets are picked 

--- Remember, you and your group will be giving speed presentations on your work at the end of the semester


## Proposal 

-- To help you think about the project early, so you can get a head start on finding data, reading relevant literature, thinking about the questions you wish to answer, etc.

-- To ensure that the data you wish to analyze, methods you plan to use, and the scope of your analysis are feasible and will allow you to be successful for this project.

## Requirements 

-- Select 3 data sets that meet the criteria 

-- Ask a research question that can be answered (see HW / Lab / Exam questions for examples). Note: These may change as we learn more throughout the semester and that is okay!

-- Find one piece of literature relavent to your research topic and summarize it

-- Load in your data and run `glimpse` so we can see it

## Data Set 

-- 300 + Observations 

-- 6 "useful" variables 

-- Must be a real data set 

## Research Question 

-- Using key phrases like "assessing relationships between...." 

-- Your research question can have more than 1 part.

-- Can it be answered? 

## Literature Review 

-- Find one published credible article on the topic you are interested in researching.

-- Provide a one paragraph summary about the article.

-- In 1-2 sentences, explain how your research question builds on / is different than the article you have cited.

You can find articles using Google Scholar or some other academic search engine. Please reach out if you have any questions about this.

## Glimpse of Data 

-- First, you must load your csv into your *data* folder in your project repo. 

-- Next use `name.of.data <- read_csv("data/name.of.file.csv")` to load your data into R. 

--- AE-05 has an example on how to load in data.


