{
  "hash": "b13794d333cde902f8937118889f5ecc",
  "result": {
    "markdown": "---\ntitle: \"Finish CLT + Hypothesis Testing\"\nsubtitle: \"Suggested Answers\"\ncategories: \n  - Application exercise\neditor: visual\n---\n\n\n## Iris Data\n\nThe Iris Dataset contains four features (length and width of sepals and petals) of 50 samples of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). A sepal is the outer parts of the flower (often green and leaf-like) that enclose a developing bud. The petal are parts of a flower that are the pollen producing part of the flower that are often conspicuously colored. The difference between sepals and petals can be seen below.\n\nThe data were collected in 1936 at the Gaspé Peninsula, in Canada. For the first question of the exam, you will use this data sets to investigate a variety of relationships to learn more about each of these three flower species. The data set is prepackaged in R, and is called `iris`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──\n✔ ggplot2 3.4.0     ✔ purrr   0.3.5\n✔ tibble  3.1.8     ✔ dplyr   1.0.9\n✔ tidyr   1.2.1     ✔ stringr 1.4.1\n✔ readr   2.1.3     ✔ forcats 0.5.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyr' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readr' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'purrr' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidymodels)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──\n✔ broom        1.0.1     ✔ rsample      1.1.0\n✔ dials        1.1.0     ✔ tune         1.0.1\n✔ infer        1.0.3     ✔ workflows    1.1.0\n✔ modeldata    1.0.1     ✔ workflowsets 1.0.0\n✔ parsnip      1.0.3     ✔ yardstick    1.1.0\n✔ recipes      1.0.3     \n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'broom' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'dials' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'parsnip' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'recipes' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──\n✖ scales::discard() masks purrr::discard()\n✖ dplyr::filter()   masks stats::filter()\n✖ recipes::fixed()  masks stringr::fixed()\n✖ dplyr::lag()      masks stats::lag()\n✖ yardstick::spec() masks readr::spec()\n✖ recipes::step()   masks stats::step()\n• Search for functions across packages at https://www.tidymodels.org/find/\n```\n:::\n\n```{.r .cell-code}\nlibrary(openintro)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: airports\nLoading required package: cherryblossom\nLoading required package: usdata\n\nAttaching package: 'openintro'\n\nThe following object is masked from 'package:modeldata':\n\n    ames\n```\n:::\n\n```{.r .cell-code}\ndata(iris)\n```\n:::\n\n\nBelow, we are going to use theory based + simulation techniques to calculate a confidence interval and theory based techniques to conduct a hypothesis test. Note: we are interested in the true mean sepal length between the setosa and versicolor species.\n\nCreate a data set called `iris_filter` that removes the species `virginica`. After this, check the levels for the variable `Species`. Is `virginica` still there? Let's drop it!\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris_filter <- iris |>\n  filter(Species != \"virginica\") |>\n  droplevels()\n```\n:::\n\n\n## Theory Based\n\nThe t-distribution can be used for inference when working with a quantitative response if the following conditions hold:\n\n**Independence**\n\n**Large samples and no extreme outliers**\n\nLet's first **estimate** what our population parameter may be.\n\n-- Write out our population parameter in proper notation (s-v)\n\n$\\mu_s - \\mu_v$\n\n-- Next, calculate and write out our estimate. Name this value `estimate`. Use s-v for your order of subtraction.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#define your difference in means as your estimate below\n\nestimate <- iris_filter |>\n  specify(response = Sepal.Length, explanatory = Species) |>\n  calculate(stat = \"diff in means\", order = c(\"setosa\", \"versicolor\")) |>\n  as.numeric()\n\n\niris_filter |>\n  group_by(Species) |>\n  summarize(mean_diff = mean(Sepal.Length))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  Species    mean_diff\n  <fct>          <dbl>\n1 setosa          5.01\n2 versicolor      5.94\n```\n:::\n:::\n\n\nLet's remind ourselves on how we calculate our confidence interval below\n\n![](images/me.png)\n\nTo do this, let's define each piece. Let's calculate our 95% confidence interval. Recall that we need to define our degrees of freedom! Commonly, we use `min(n1-1; n2-1)`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndef <- iris_filter |>\n  group_by(Species) |>\n  summarise(sample_n = n()) |>\n  pull() |>\n  min() - 1\n\nt_star <- qt(0.975, def) \n  \nsd1 <- iris_filter |>\n  filter(Species == \"setosa\") |>\n  summarize(sd_s = sd(Sepal.Length)) |>\n  as.numeric()\n  \nn1 <- iris_filter |>\n  filter(Species == \"setosa\") |>\n  summarize(s_n = n()) |>\n  as.numeric()\n\nsd2 <- iris_filter |>\n  filter(Species == \"versicolor\") |>\n  summarize(sd_v = sd(Sepal.Length)) |>\n  as.numeric()\n\nn2 <- iris_filter |>\n  filter(Species == \"versicolor\") |>\n  summarize(v_n = n()) |>\n  as.numeric()\n```\n:::\n\n\nNow, let's create our 95% confidence interval!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate + t_star * (sqrt(((sd1^2)/n1) + ((sd2^2)/n2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.7523641\n```\n:::\n\n```{.r .cell-code}\nestimate - t_star * (sqrt(((sd1^2)/n1) + ((sd2^2)/n2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -1.107636\n```\n:::\n:::\n\n\n$\\mu_s - \\mu_v$\n\n(-1.107, -0.752)\n\nNow, interpret your confidence interval in the context of the problem.\n\nWe are 95% confident that the true mean sepal length for setosa is 0.752 to 1.107 less than the true mean sepal length for versicolor.\n\n## Bootstrap Methods\n\nDo we expect the results to be the same for bootstrap methods? Why or why not?\n\n**Yes. There is no evidence to suggest that the CLT assumptions were violated.**\n\nNow, let's simulate our bootstrap distribution below. Detail how one observation on this bootstrap distribution is created.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\n\nboot_dist <- iris_filter |>\n  specify(response = Sepal.Length, explanatory = Species) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"diff in means\" , order = c(\"setosa\" , \"versicolor\"))\n\n\nboot_dist |>\n  ggplot(\n    aes(x = stat)\n  ) + \n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](ae-15-sa_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n**Resample within replacement within each group n1 and n2 number of times. Calculate the new sample means. Take the difference. Do this process a large number of times (1000).**\n\nAnd finally, calculate your confidence interval here...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_dist |> \n  summarize(lower = quantile(stat, 0.025),\n            upper = quantile(stat, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  lower  upper\n  <dbl>  <dbl>\n1 -1.11 -0.757\n```\n:::\n:::\n\n\nTheory: (-1.107, -0.752) Simulation: (-1.11 , -0.765)\n\nNow, suppose we want to test to see if there is a difference in sepal length across the two species. Let's do this below!\n\nNote: The confidence level is equivalent to 1 -- the **alpha level**. So, if your significance level is 0.05, the corresponding confidence level is 95%.\n\nIn short, would we expect to reject or fail to reject our null hypothesis based on our results from our confidence interval?\n\n**Yes! 0 is not a plausible value given based on our confidence interval. At a 5% significance level, our 95% confidence interval suggests that we will reject the null hypothesis.**\n\n## Steps for Hypothesis Test (Theory Based)\n\nSteps:\n\n1)  Check assumptions - check\n\n2)  Calculate sample mean - check\n\n3)  Calculate SE\n\n4)  Use 2 & 3 to calculate t-statistic\n\n5)  Calculate p-value\n\nLet's remind ourselves what the difference in means (s - v) are below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.93\n```\n:::\n:::\n\n\nTo \"standardize our statistic\"... we need to divide by the standard error. The standard error of the different in sample means can be calculated as follows:\n\n![](images/se.png)\n\nWe can calculate your t-statistic using the following formula below:\n\n![](images/t-stat.png)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntscore <- (estimate - 0) / sqrt(((sd1^2)/n1) + ((sd2^2)/n2))\n```\n:::\n\n\nWe use `pt` to calculate our p-value. Recall that we need to define our degrees of freedom! Commonly, we use `min(n1-1; n2-1)`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(tscore , df = 49) * 2 #multiply by 2 for two sided test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.63027e-14\n```\n:::\n:::\n\n\nWrite an appropriate scope of inference in the context of the problem below:\n\nAssuming that these observations of plants are a representative sample, we can conclude a difference in true mean sepal length between setosa and versicolor species at the population level. Because this is an observational study, we can infer an association between species and sepal length.\n",
    "supporting": [
      "ae-15-sa_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}