{
  "hash": "eb2c6da0c3b7fac4452771159c125843",
  "result": {
    "markdown": "---\ntitle: \"Inference Overview\"\nformat: html\neditor: visual\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'ggplot2' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'tidyr' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readr' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'purrr' was built under R version 4.2.2\n```\n:::\n\n```{.r .cell-code}\nlibrary(tidymodels)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'broom' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'dials' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'parsnip' was built under R version 4.2.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'recipes' was built under R version 4.2.2\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nrc <- read_csv(\"data/roller_coasters.csv\")\n\nrc <- na.omit(rc) #remove all NA values from data set\n```\n:::\n\n\nIn this application exercise, we will be looking at a roller coaster and amusement park database by Duane Marden.[^1] This database records multiple features of roller coasters. For the purpose of this activity, we will work with a random sample of 157 roller coasters.\n\n[^1]: [Roller Coaster DataBase](https://rcdb.com/), [UltimateRollerCoaster.com](https://www.ultimaterollercoaster.com/), [ESTEEM: Enhancing Statistics Teachers Education with E-Modules](https://www.fi.ncsu.edu/teams/hirise/).\n\n+---------------------+--------------------------------------------------------------------------+\n| **Variable**        | **Description**                                                          |\n+:====================+:=========================================================================+\n| `age_group`         | 1: Older (Built between 1900-1979)                                       |\n|                     |                                                                          |\n|                     | 2: Recent (1980-1999)                                                    |\n|                     |                                                                          |\n|                     | 3: Newest (2000-current)                                                 |\n+---------------------+--------------------------------------------------------------------------+\n| `coaster`           | Name of the roller coaster                                               |\n+---------------------+--------------------------------------------------------------------------+\n| `park`              | Name of the park where the roller coaster is located                     |\n+---------------------+--------------------------------------------------------------------------+\n| `city`              | City where the roller coaster is located                                 |\n+---------------------+--------------------------------------------------------------------------+\n| `state`             | State where the roller coaster is located                                |\n+---------------------+--------------------------------------------------------------------------+\n| `type`              | Material of track (Steel or Wooden)                                      |\n+---------------------+--------------------------------------------------------------------------+\n| `year_opened`       | Year when roller coaster opened                                          |\n+---------------------+--------------------------------------------------------------------------+\n| `top_speed`         | Maximum speed of roller coaster (mph)                                    |\n+---------------------+--------------------------------------------------------------------------+\n| `max_height`        | Highest point of roller coaster (ft)                                     |\n+---------------------+--------------------------------------------------------------------------+\n| `drop`              | Length of largest gap between high and low points of roller coaster (ft) |\n+---------------------+--------------------------------------------------------------------------+\n| `length`            | Length of roller coaster track (ft)                                      |\n+---------------------+--------------------------------------------------------------------------+\n| `duration`          | Time length of roller coaster ride (sec)                                 |\n+---------------------+--------------------------------------------------------------------------+\n| `inversions`        | Whether or not roller coaster flips passengers at any point (Yes or No)  |\n+---------------------+--------------------------------------------------------------------------+\n| `num_of_inversions` | Number of times roller coaster flips passengers                          |\n+---------------------+--------------------------------------------------------------------------+\n\n## Practice with data manipulation\n\n-   **Demo:** Create a new variable called `opened_recently` that has a response of `yes` if the roller coaster was opened after 1970, and `no` if the roller coaster was built during or before 1970. Save this new factor variable in the `rc` data set. Additionally, make `type` a factor variable.\n\nRead each line of code below as a sentence to ensure you understand what each line of code is doing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrc <- rc |>\n  mutate(\n    opened_recently = if_else(year_opened > 1970, \"yes\", \"no\"), \n    opened_recently = as.factor(opened_recently),\n    type = as.factor(type)\n  ) \n```\n:::\n\n\n\n# Confidence Intervals\n\n> **We are interested in investigating if roller coasters after 1970 are faster than those opened before. For this question, we want to estimate the difference.**\n\nWhat is our explanatory variable? \n\nWhat is our response variable? \n\nx – opened_recently \n\ny – top_speed \n\n\n-   **Demo:** Use bootstrapping to estimate the difference between the true speeds of roller coasters before and after 1970.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(12345)\n\nboot_df <- rc |>\n  specify(explanatory  = opened_recently , response = top_speed) |>\n  generate(reps = 1000, type = \"bootstrap\") |>\n  calculate(stat = \"diff in means\", order = c(\"yes\", \"no\"))\n```\n:::\n\n\n-   **Your turn:** Create a 99% confidence interval and interpret it in the context of the data and the research question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboot_df |>\n  summarize(\n    lower = quantile(stat, 0.005),\n    upper = quantile(stat, 0.995)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 2\n  lower upper\n  <dbl> <dbl>\n1  8.28  24.4\n```\n:::\n:::\n\n\nORDER MATTERS (yes - no)\n\nInterpretation: We are 99% confident that the true mean speed for roller coasters opened after 1970 ($\\mu_1$) is (9.15, 23) mph LARGER than the true mean speed for roller coasters opened before 1970 ($\\mu_2$)\n\nNow, calculate your confidence interval using theoretical measures\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspeed <- rc |>\n  group_by(opened_recently) |>\n  summarize(mean_speed = mean(top_speed, na.rm = T)) |>\n  pull(mean_speed)\n\n#remind us of sample sizes\nrc |>\n  group_by(opened_recently) |>\n  summarize(groups = n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 2\n  opened_recently groups\n  <fct>            <int>\n1 no                  10\n2 yes                105\n```\n:::\n\n```{.r .cell-code}\nobs_stat <- speed[2] - speed[1]\n\nn1 <- 16\n\nn2 <- 141\n\ns1 <- rc |> \n  filter(opened_recently == \"yes\") |>\n  summarise(sd_s = sd(top_speed, na.rm = T)) |>\n  pull()\n\ns2 <- rc |> \n  filter(opened_recently == \"no\") |>\n  summarise(sd_s = sd(top_speed, na.rm = T)) |>\n  pull()\n\nobs_stat + qt(0.995, df = 15) * (sqrt(((s1^2)/n1) + ((s2^2)/n2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 25.8743\n```\n:::\n\n```{.r .cell-code}\nobs_stat - qt(0.995, df = 15) * (sqrt(((s1^2)/n1) + ((s2^2)/n2)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4.478077\n```\n:::\n:::\n\n\n\n# Hypothesis Test\n\nDo steel roller coasters have more inversions than wooden roller coasters? Conduct a hypothesis test using simulation techniques. \n\nHo: The true proportion of inversions on steel roller coasters is equal to the true proportion of inversions on a wooden roller coaster.\n\nHa: The true proportion of inversions on steel roller coasters is less than the true proportion of inversions on a wooden roller coaster.\n\n-- Now calculate your statistic below\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstat_df <- rc |>\n  group_by(inversions, type) |>\n  summarize(props = n()) |>\n  pull(props)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n`summarise()` has grouped output by 'inversions'. You can override using the\n`.groups` argument.\n```\n:::\n\n```{.r .cell-code}\nsteel_stat <- stat_df[3]/(stat_df[1] + stat_df[2])\nwood_stat <- stat_df[4]/(stat_df[3] + stat_df[4])\n\nobs_stat <- steel_stat - wood_stat\n```\n:::\n\n\n-- Create your null distribution, explain how this distribution is being created\n\n\n::: {.cell}\n\n```{.r .cell-code}\npermute_df <- rc |>\n  specify(response = inversions , explanatory = type , success = \"Y\") |>\n  hypothesise(null = \"independence\") |>\n  generate(reps = 1000, type = \"permute\") |>\n  calculate(stat = \"diff in props\", order = c(\"Steel\", \"Wooden\"))\n```\n:::\n\n\n\n-- Calculate your p-value below\n\n\n::: {.cell}\n\n```{.r .cell-code}\npermute_df |>\n  get_p_value(obs_stat = obs_stat, direction = \"right\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Please be cautious in reporting a p-value of 0. This result is an\napproximation based on the number of `reps` chosen in the `generate()` step. See\n`?get_p_value()` for more information.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  p_value\n    <dbl>\n1       0\n```\n:::\n:::\n\n\n\nNow, calculate your p-value using theoretical measures\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_pool <- (stat_df[3] + stat_df[4]) / nrow(rc) \n\nse <- sqrt(p_pool*(1-p_pool)*((1/79) + (1/36)))\n\nzscore <- obs_stat / se\n\npnorm(zscore, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9.080354e-14\n```\n:::\n:::\n\n\n# Fitting a Model: Prediction \n\n> **We want to investigate the relationship between how fast a roller coaster goes, and how long a roller coaster lasts. Specifically, we are interested in how well the duration of a roller coaster explains how fast it is.**\n\n-   **Your turn:** Based on this research question, which two variables should we use from our data set? Which is our response?\n\n**Add Response**\n\nNow let's practice predicting!\n\n-   **Demo:** Fit the appropriate linear model below. Report the tidy output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspeed_fit <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(top_speed ~ duration, data = rc) \n\ntidy(speed_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic  p.value\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)  52.7       4.36       12.1  4.52e-22\n2 duration      0.0513    0.0327      1.57 1.20e- 1\n```\n:::\n:::\n\n\n-   Write estimated model in proper notation below:\n\n$\\hat{speed} = 52.7 + 0.0513*duration$\n\n-   **Demo:** Use your model to estimate the top speed of a roller coaster if their duration is 155 minutes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nduration_155 <- tibble(duration = 155)\n\npredict(speed_fit, new_data = duration_155)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1  60.6\n```\n:::\n:::\n\n\n## Interpret\n\n-   Now, interpret the slope coefficient.\n\n**For a 1 minute increase in duration, we estimate on average a 0.0513 mph increase in speed.**\n\n\n- We extended this idea to: \n\nMultiple Linear Regression \n\nLogistic Regression \n\nand compared models using R-squared (if we had the same number of coefficients; adjusted-r-squared, and AIC)\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}