{
  "hash": "53cbbd32621f044044c0025383dc768e",
  "result": {
    "markdown": "---\ntitle: \"Regression with a Multiple Predictors\"\nsubtitle: \"Suggested Answers\"\ncategories: \n  - Application exercise\neditor: visual\n---\n\n\n## Packages\n\nNote - if you don't have the plotly or widgetframe package, you can install these before running `library` by writing the following code in the console:\n\ninstall.packages(\"plotly\") install.packages(\"widgetframe\")\n\nThese packages are not necessary to finish the AE.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(palmerpenguins)\nlibrary(plotly)\nlibrary(widgetframe)\n```\n:::\n\n\n## Finishing SLR\n\nNow, fit the linear regression model and display the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ island, data = penguins) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term            estimate std.error statistic   p.value\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        4716.      48.5      97.3 8.93e-250\n2 islandDream       -1003.      74.2     -13.5 1.42e- 33\n3 islandTorgersen   -1010.     100.      -10.1 4.66e- 21\n```\n:::\n:::\n\n\nInterpret the intercept term in the context of the problem:\n\n**For a penguin on the Biscoe island, the estimated mean body mass is roughly 4716 g.**\n\nInterpret the Dream coefficient in the context of the problem:\n\n**For a penguin on the Dream island, the estimated mean body mass is roughly 4716 - 1003 g.** OR\n\nFor a penguin on the Dream island, the estimated mean body mass is roughly 1003 g less than the estimated mean body mass for a penguin on the Bisoce island.\n\n## Changing the intercept\n\nOften times, we want to take control of what the intercept is. We can do this by changing the levels of the categorical variable prior to fitting the model using `fct_relevel`. Save over the original penguins data set for this example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin.new <- penguins |>\n  mutate(island = fct_relevel(island, levels = \"Dream\", \"Biscoe\", \"Torgersen\"))\n\nlinear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ island, data = penguin.new) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 5\n  term            estimate std.error statistic   p.value\n  <chr>              <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)      3713.        56.2   66.0    1.44e-195\n2 islandBiscoe     1003.        74.2   13.5    1.42e- 33\n3 islandTorgersen    -6.53     104.    -0.0627 9.50e-  1\n```\n:::\n:::\n\n\n## Multiple Linear Regression\n\n### Additive model\n\nIn the last class, we modeled body mass by flipper length and also by island. Could it be possible that the estimated body mass of a penguin changes by both their flipper length AND by the island they are on?\n\nIn multiple linear regression, we will discuss two different types of models. Additive models and interaction models. What's the difference?\n\nAdditive models: **The relationship between x and y does not change based on z**\n\nInteraction models: **The relationship between x and y does change by z**\n\nNow, fit an *additive* model to assess the relationship between our response variable body mass, and our explanatory variables flipper length and island. Produce the summary output. Write out the estimate regression equation below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ flipper_length_mm + island, data = penguins)\n```\n:::\n\n\n$\\widehat{body\\_mass} = -4625 + 44.5*flipper\\_length - 262*Dream - 185*Torgersen$\n\n$I_t {1 if Torgersen; 0 else}$\n\n$I_d {1 if Dream; 0 else}$\n\n-- Interpret the slope coefficient for flipper length in the context of the problem\n\n**Holding island constant, for a 1 mm increase in flipper length, we estimate on average a 44.54 g increase in body mass**\n\n-- Interpret the slope coefficient for Dream island in the context of the problem\n\n**Holding flipper length constant, we estimate the mean body mass for penguins on the dream island to be -262.18g less than those on the Biscoe island.**\n\n-- Predict the body mass of a penguin with a flipper length of 200 on the Dream island\n\nNote: Above....name your model and do not pipe it into `tidy()` if you want to use the `predict` function. Next, fill in the code below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(model1, data.frame(flipper_length_mm = 200, island = \"Dream\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 4021.\n```\n:::\n:::\n\n\n## Interaciton Model\n\nWhat changes in the R code when fitting an interaction model instead of an additive model in R?\n\n**+ to a \\***\n\n-- Now fit the interaction model. Display the summary output and write out the estimate regression equation below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nint_model <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ flipper_length_mm * island, data = penguins)\n```\n:::\n\n\n$\\widehat{body\\_mass} = -5464 + 48.5*flipper + 3551*Dream + 3218*Torg -19.4*flipper*Dream - 17.4*flipper*Torg$\n\nWhat does it mean for island and flipper length to interact? How do we interpret an interaction effect?\n\n**This means that the relaionship between body mass and flipper length depends on the island the penguin was located on**\n\nNow, name your interaction model `int_model` and remove the tidy() from the pipeline. Use this named model to make this prediction below.\n\n-- Predict the body mass of a penguin with a flipper length of 200 on the Dream island\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(int_model, data.frame(flipper_length_mm = 200, island = \"Dream\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 1\n  .pred\n  <dbl>\n1 3915.\n```\n:::\n:::\n\n\n## How do we talk about interaction terms?\n\nNo general interpretation like with main effects\n\nDiscuss in general: The relationship between mean body mass and penguin's flipper length changes based on island + describe the plot\n\nWe can then use these estimates for prediction (as seen above)\n\n## How can we choose?\n\n-- What is R-squared (reminder)? What is adjusted R-squared?\n\nR-squared is the percent variability in the response that is explained by our model. (Can use when models have same number of variables for model selection)\n\nAdjusted R-squared is similar, but has a penalty for the number of variables in the model. (Should use for model selection when models have different numbers of variables).\n\nHow can we calculate this in R?\n\nHint: We can use `glance(model.name)$r.squared and glance(model.name)$adj.r.squared`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglance(model1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7742334\n```\n:::\n\n```{.r .cell-code}\nglance(int_model)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7857486\n```\n:::\n\n```{.r .cell-code}\nglance(model1)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7722296\n```\n:::\n\n```{.r .cell-code}\nglance(int_model)$adj.r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7825604\n```\n:::\n:::\n\n\nWhich model should we pick? Which measure did you use to justify your decision?\n\nWe can use adjusted R squared to provide evidence to choose the interaction model over the additive one.\n\n## We can not use R-squared to compare models of different variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(333)\n\npenguins <- penguins |>\n  mutate(random = rnorm(mean = 10, sd = 2, nrow(penguins)))\n```\n:::\n\n\nNow, fit an additive model that estimates body mass by flipper length, island, AND by this random variable. What is the r-squared. How does that compare to the additive model with just flipper length and island?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrandom_model <- linear_reg() |>\n  set_engine(\"lm\") |>\n  fit(body_mass_g ~ flipper_length_mm + island + random, data = penguins) \n\nglance(random_model)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7742907\n```\n:::\n\n```{.r .cell-code}\nglance(model1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7742334\n```\n:::\n:::\n\n\nThe r-squared went up, despite adding a nonsense variable! We can not use this measure to select a model when the models have a different number of variables.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}